-- One-time backfill: move the trailing single-letter middle initial out of
-- first_name into the middle_initial column, for the imported students.
-- Run AFTER migrate-students-middle-initial.sql. Idempotent and re-runnable:
-- each row matches its exact original first_name and is skipped once moved.
SET NAMES utf8mb4;

UPDATE students SET middle_initial='L.', first_name='Jibrielle' WHERE first_name='Jibrielle L.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='E.', first_name='Jezman Wynn' WHERE first_name='Jezman Wynn E.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='E.', first_name='DANVER ZION' WHERE first_name='DANVER ZION E.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='S.', first_name='Gary Emmanuel' WHERE first_name='Gary Emmanuel S.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='P.', first_name='Gail Denise' WHERE first_name='Gail Denise P.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='V.', first_name='James Michael' WHERE first_name='James Michael V.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='L.', first_name='Yen' WHERE first_name='Yen L.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Jesselie' WHERE first_name='Jesselie C' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='L.', first_name='John Patrick' WHERE first_name='John Patrick L.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='E.', first_name='Aariene Vienice' WHERE first_name='Aariene Vienice E.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Aldwyn Jahziel' WHERE first_name='Aldwyn Jahziel C.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='Serad' WHERE first_name='Serad B.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='L.', first_name='Samantha Angela' WHERE first_name='Samantha Angela L.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='N.', first_name='Ram Morpheus' WHERE first_name='Ram Morpheus N.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='D.', first_name='Alexander Bryan' WHERE first_name='Alexander Bryan D.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='G.', first_name='Katrina' WHERE first_name='Katrina G.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='G.', first_name='Kyler James' WHERE first_name='Kyler James G.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='S.', first_name='Ariel' WHERE first_name='Ariel S.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='S.', first_name='Ryza Marie' WHERE first_name='Ryza Marie S.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='I.', first_name='Himig' WHERE first_name='Himig I.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='Rexcia Maria' WHERE first_name='Rexcia Maria B.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='O.', first_name='Michael Angelo' WHERE first_name='Michael Angelo O.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='R.', first_name='Dela Cruz Fressie' WHERE first_name='Dela Cruz Fressie R.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='E.', first_name='Aether' WHERE first_name='Aether E.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='Shayne' WHERE first_name='Shayne B.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='Yñigo Joaquin' WHERE first_name='Yñigo Joaquin A.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='E.', first_name='Mikhaela Nicole' WHERE first_name='Mikhaela Nicole E.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='R.', first_name='Glever' WHERE first_name='Glever R.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='D.', first_name='Jenny' WHERE first_name='Jenny D.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='Shek' WHERE first_name='Shek B.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='P.', first_name='Raku' WHERE first_name='Raku P.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='P.', first_name='John Brylle' WHERE first_name='John Brylle P.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='G.', first_name='Nikita Cataleya' WHERE first_name='Nikita Cataleya G.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='E.', first_name='Jayden Adriel' WHERE first_name='Jayden Adriel E.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='F.', first_name='Rigel Benjamin Zeus' WHERE first_name='Rigel Benjamin Zeus F.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='S.', first_name='Marvin' WHERE first_name='Marvin S' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='R.', first_name='Marco Luis' WHERE first_name='Marco Luis R.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Luis' WHERE first_name='Luis C.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='G.', first_name='Cafranca samuel gerard' WHERE first_name='Cafranca samuel gerard g' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='R.', first_name='Xeela Marie' WHERE first_name='Xeela Marie R.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='L.', first_name='Euan Justin,' WHERE first_name='Euan Justin, L.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='R.', first_name='Tiffany' WHERE first_name='Tiffany R.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Emma Noelle' WHERE first_name='Emma Noelle M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='L.', first_name='Pedro IV' WHERE first_name='Pedro IV L.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='J.', first_name='Yohan Miguel' WHERE first_name='Yohan Miguel J.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='T.', first_name='Franco Andres,' WHERE first_name='Franco Andres, T' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Joshua' WHERE first_name='Joshua C' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='THOMAS ROBERT' WHERE first_name='THOMAS ROBERT A.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='D.', first_name='Edmond Philip' WHERE first_name='Edmond Philip D.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='Jp Ezikiel' WHERE first_name='Jp Ezikiel A.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='Kathleen Dale' WHERE first_name='Kathleen Dale B.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='F.', first_name='Alejandro' WHERE first_name='Alejandro F.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='N.', first_name='Kim Lemuel,' WHERE first_name='Kim Lemuel, N.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='D.', first_name='John Carlo' WHERE first_name='John Carlo D' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='Vince Jandel Niño' WHERE first_name='Vince Jandel Niño A.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Mark Kevin' WHERE first_name='Mark Kevin C.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='Ryzhick' WHERE first_name='Ryzhick B.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='Martin Jr' WHERE first_name='Martin Jr A.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='V.', first_name='Dan' WHERE first_name='Dan V.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Ruah Alexzander' WHERE first_name='Ruah Alexzander C.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='E.', first_name='Marlea Leavin' WHERE first_name='Marlea Leavin E.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='S.', first_name='Ramento Jerry' WHERE first_name='Ramento Jerry S' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='S.', first_name='Jynkee Lyn' WHERE first_name='Jynkee Lyn S.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='L.', first_name='Xavi Ethan' WHERE first_name='Xavi Ethan L.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='J.', first_name='Yohan Miguel Federizo' WHERE first_name='Yohan Miguel Federizo J.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='G.', first_name='Catherine' WHERE first_name='Catherine G.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='Anne Marichy' WHERE first_name='Anne Marichy B.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='Villalon Jason' WHERE first_name='Villalon Jason B' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='John Michael' WHERE first_name='John Michael M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='R.', first_name='Colleen Marhey' WHERE first_name='Colleen Marhey R.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='U.', first_name='Jefferson' WHERE first_name='Jefferson U.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='G.', first_name='Julius' WHERE first_name='Julius G.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Kent Joel' WHERE first_name='Kent Joel M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='P.', first_name='Angelo' WHERE first_name='Angelo P.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='E.', first_name='Patrick' WHERE first_name='Patrick E.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Neil Martin' WHERE first_name='Neil Martin M' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='Michael' WHERE first_name='Michael A.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Mariela Camile' WHERE first_name='Mariela Camile M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='Kirsten' WHERE first_name='Kirsten A.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='L.', first_name='Steve' WHERE first_name='Steve L' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Paulyn' WHERE first_name='Paulyn M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='T.', first_name='Romel' WHERE first_name='Romel T.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='E.', first_name='Patricio Joven' WHERE first_name='Patricio Joven E.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='R.', first_name='Humprey' WHERE first_name='Humprey R.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Mattthew' WHERE first_name='Mattthew M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='D.', first_name='Jamhire' WHERE first_name='Jamhire D.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Costales Jonathan' WHERE first_name='Costales Jonathan C' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='T.', first_name='Michael John' WHERE first_name='Michael John T.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='V.', first_name='Jonyl' WHERE first_name='Jonyl V.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='D.', first_name='Sean Willowy' WHERE first_name='Sean Willowy D.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Ariane' WHERE first_name='Ariane M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='Aeron' WHERE first_name='Aeron B' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='JONARD' WHERE first_name='JONARD B.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='N.', first_name='Kevin' WHERE first_name='Kevin N' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='J.', first_name='Chevron,' WHERE first_name='Chevron, J.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='F.', first_name='Katherine Rose' WHERE first_name='Katherine Rose F.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Ezekiel' WHERE first_name='Ezekiel M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='D.', first_name='Mark Pollen' WHERE first_name='Mark Pollen D' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='R.', first_name='Kaye' WHERE first_name='Kaye R.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='P.', first_name='Celajes Von' WHERE first_name='Celajes Von P.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='L.', first_name='Jeremiah Joseph' WHERE first_name='Jeremiah Joseph L.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='P.', first_name='Kyrie' WHERE first_name='Kyrie P.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Reil Joseph' WHERE first_name='Reil Joseph M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Jean Christopher' WHERE first_name='Jean Christopher M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='S.', first_name='Genesis Luiz' WHERE first_name='Genesis Luiz S.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Dos Franco' WHERE first_name='Dos Franco C.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='F.', first_name='Jumar' WHERE first_name='Jumar F.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='L.', first_name='Avery Marels' WHERE first_name='Avery Marels L.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Sean Nicholai' WHERE first_name='Sean Nicholai C.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='S.', first_name='Ethan James' WHERE first_name='Ethan James S.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='G.', first_name='Maria Marcella' WHERE first_name='Maria Marcella G.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='G.', first_name='Paul' WHERE first_name='Paul G.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='Richard Gabriel' WHERE first_name='Richard Gabriel B.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='S.', first_name='Genesis' WHERE first_name='Genesis S.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='V.', first_name='Saloma Sammy' WHERE first_name='Saloma Sammy V.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='P.', first_name='Errol Aaron' WHERE first_name='Errol Aaron P.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Cain Daniel' WHERE first_name='Cain Daniel M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='G.', first_name='Donna Mae' WHERE first_name='Donna Mae G.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Lady Mae Karylle' WHERE first_name='Lady Mae Karylle C.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Will' WHERE first_name='Will C' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='Elizabeth' WHERE first_name='Elizabeth B.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='L.', first_name='Loreybelle,' WHERE first_name='Loreybelle, L' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='J.', first_name='Micah' WHERE first_name='Micah J.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='L.', first_name='Anne Loraine' WHERE first_name='Anne Loraine L.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='S.', first_name='Rex Philip' WHERE first_name='Rex Philip S' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='V.', first_name='Kelly Brent' WHERE first_name='Kelly Brent V' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='S.', first_name='Vann Dirksen' WHERE first_name='Vann Dirksen S.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='S.', first_name='Bernardo Bryan' WHERE first_name='Bernardo Bryan S.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='V.', first_name='John Dave' WHERE first_name='John Dave V.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='D.', first_name='Kalle Nimshi' WHERE first_name='Kalle Nimshi D.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='ERIC' WHERE first_name='ERIC B.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Josiah Emmanuel' WHERE first_name='Josiah Emmanuel M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='T.', first_name='Aldhean' WHERE first_name='Aldhean T' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='Mary Dominique' WHERE first_name='Mary Dominique A.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Judah Timothy' WHERE first_name='Judah Timothy C.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Arin Mykel' WHERE first_name='Arin Mykel M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='S.', first_name='Julie Ann' WHERE first_name='Julie Ann S' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='D.', first_name='Deyra' WHERE first_name='Deyra D.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='L.', first_name='Seve Philip' WHERE first_name='Seve Philip L.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='V.', first_name='Mariz' WHERE first_name='Mariz V.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='S.', first_name='Zul' WHERE first_name='Zul S.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='R.', first_name='Jack Russel' WHERE first_name='Jack Russel R.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='D.', first_name='Psalm' WHERE first_name='Psalm D' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='Eric' WHERE first_name='Eric B' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='R.', first_name='Maria Angela' WHERE first_name='Maria Angela R.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='Sean Carlos' WHERE first_name='Sean Carlos A.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='F.', first_name='Lourdelito' WHERE first_name='Lourdelito F.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='P.', first_name='Nikolai Ezio' WHERE first_name='Nikolai Ezio P' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Mateo Zion' WHERE first_name='Mateo Zion C.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Jelo' WHERE first_name='Jelo M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='T.', first_name='Alyssa Sandrea' WHERE first_name='Alyssa Sandrea T.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='G.', first_name='Risando' WHERE first_name='Risando G.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='P.', first_name='Nikolai Ezio' WHERE first_name='Nikolai Ezio P.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='E.', first_name='Jhovenell' WHERE first_name='Jhovenell E.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Apollo Darwin' WHERE first_name='Apollo Darwin C.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='P.', first_name='Thomas Jeffrey' WHERE first_name='Thomas Jeffrey P.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='C.', first_name='Danilo' WHERE first_name='Danilo C' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='O.', first_name='Alyzza' WHERE first_name='Alyzza O.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='R.', first_name='Agnes Marie' WHERE first_name='Agnes Marie R.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='Joshua Dave' WHERE first_name='Joshua Dave A.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='G.', first_name='Patrick Neil' WHERE first_name='Patrick Neil G.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='L.', first_name='Jhana Mae' WHERE first_name='Jhana Mae L' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='P.', first_name='Adrian' WHERE first_name='Adrian P.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='V.', first_name='Morwin' WHERE first_name='Morwin V.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='Mariela' WHERE first_name='Mariela B.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='Ryan Joaquin' WHERE first_name='Ryan Joaquin A.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='T.', first_name='Jemimah Emerald' WHERE first_name='Jemimah Emerald T.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='E.', first_name='John Angelo' WHERE first_name='John Angelo E.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='E.', first_name='Hazel Angelyn' WHERE first_name='Hazel Angelyn E.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='Joel Cleon' WHERE first_name='Joel Cleon A.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='Allexa' WHERE first_name='Allexa A.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='Alonzo Marlon' WHERE first_name='Alonzo Marlon A.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='E.', first_name='San Agustin Joshua Immanuel' WHERE first_name='San Agustin Joshua Immanuel E.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='M.', first_name='Roz william' WHERE first_name='Roz william M.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='B.', first_name='Quinn Zypel' WHERE first_name='Quinn Zypel B.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='L.', first_name='Martin Miguel' WHERE first_name='Martin Miguel L.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='P.', first_name='Liam Raphael' WHERE first_name='Liam Raphael P.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='G.', first_name='Mark Jude' WHERE first_name='Mark Jude G.' AND (middle_initial IS NULL OR middle_initial='');
UPDATE students SET middle_initial='A.', first_name='Herbert Austin' WHERE first_name='Herbert Austin A.' AND (middle_initial IS NULL OR middle_initial='');
